# Generated by Django 5.1.7 on 2025-03-18 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetaYprotocolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_protocols', to='etiquetaYprotocolo.service'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='etiquetaYprotocolo.servicerequest'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='etiquetaYprotocolo.company'),
        ),
        migrations.AlterField(
            model_name='service',
            name='protocols',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='protocols',
            field=models.ManyToManyField(blank=True, to='etiquetaYprotocolo.protocol'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='etiquetaYprotocolo.service'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tags',
            field=models.ManyToManyField(blank=True, to='etiquetaYprotocolo.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tags', to='etiquetaYprotocolo.service'),
        ),
    ]
