# Generated by Django 5.1.7 on 2025-03-19 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetaYprotocolo', '0002_alter_company_nit_alter_protocol_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='protocols',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.AlterField(
            model_name='protocol',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_list', to='etiquetaYprotocolo.service'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etiquetaYprotocolo.servicerequest'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiquetaYprotocolo.company'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='protocols',
            field=models.ManyToManyField(to='etiquetaYprotocolo.protocol'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiquetaYprotocolo.service'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tags',
            field=models.ManyToManyField(to='etiquetaYprotocolo.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_list', to='etiquetaYprotocolo.service'),
        ),
    ]
